logging:
  level.: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xxxxx
    username: root
    password: sql2016.
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8865

security:
  jwt:
    token:
      uri: /authenticate
      expiration: 604800
      secretKey: mySecret
